# Application Name and Version
Application = "GLOBAL.MedImpact Healthcare Systems Inc.DevSecOps.WebGoat"
Application_Version = "1.0.0"

# Define Component Name, Variant and Version
Name = "GLOBAL.MedImpact Healthcare Systems Inc.DevSecOps.ms-ic-webgoat"
Variant = "${GIT_BRANCH}"
Version = "v1.0.0.${BUILD_NUM}-g${SHORT_SHA}"


# Key/Values to associate to the Component Version
[Attributes]
    DiscordChannel = "https://discord.gg/wM4b5yEFzS"
    ServiceOwner= "${DHUSER}"
    ServiceOwnerEmail = "indrajit.chauhan@gmail.com"
